lab4/urls.py
from django.contrib import admin
from django.urls import include, path
from story4.views import home as page1
from story4.views import about as page2
from story4.views import experience as page3
from story4.views import project as page4
from story4.views import form as page5
from django.urls import path, include
from django.urls import re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
        path('', include(('story5.urls', 'story5'), namespace="story5")),
   	re_path(r'^$', page1, name= "home"),
    re_path(r'^home', page1, name="home"),  
 	re_path(r'^about', page2, name="about"),
 	re_path(r'^experience', page3, name="experience"),
 	re_path(r'^project', page4, name="project"),
 	re_path(r'^form', page5, name="form")

]

story4/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	
]

story5/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addproject/', views.addproject, name='addproject'),
    path('saveproject/', views.saveproject, name='saveproject'),
    path('delete_every/', views.delete_every, name='delete_every'),
]

story4/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models
from django.utils import timezone
from datetime import date
# Create your models here.
class Project(models.Model):
	position = models.CharField(max_length=200)
	title = models.CharField(max_length=200)
	description = models.TextField()
	tanggal = models.DateField(default=date.today)
	kategori = models.CharField(max_length = 200)
	time = models.TimeField(auto_now = False, auto_now_add = False)

story5/forms.py
from django import forms
import datetime
class Add_Project_Form(forms.Form):
    error_messages = {
        'required': 'Please type',
    }
    position_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Nama Kegiatan'
    }

    date_attrs = {
        'type': 'date',
        'class': 'todo-form-input',
    }
    title_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Tempat Kegiatan'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Deskripsi Kegiatan'
    }
    OPTION = {
        ('Akademis', 'Akademis'),
        ('Kepanitiaan', 'Kepanitiaan'),
        ('Organisasi', 'Organisasi'),
        ('Lainnya', 'Lainnya')
    }


    position = forms.CharField(label='Nama Kegiatan', required=True, max_length=27, widget=forms.TextInput(attrs=position_attrs))
    title = forms.CharField(label='Tempat Kegiatan', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    description = forms.CharField(label='Deskrpsi Kegiatan', required=True, widget=forms.Textarea(attrs=description_attrs))
    tanggal = forms.DateField(required=True,initial=datetime.date.today, widget = forms.DateInput(attrs = {'type' : 'date'}))
    kategori = forms.ChoiceField(choices = OPTION)
    time = forms.TimeField(widget = forms.TimeInput(attrs = {'type' : 'time'}))

story4/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def index(request):
	return render(request, 'Home.html')

def home(request):
	return render(request, 'Home.html')

def about(request):
	return render(request, 'About.html')

def experience(request):
	return render(request, 'Experience.html')

def project(request):
	return render(request, 'Project.html')

def form(request):
	return render(request, 'Form.html')

story5/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Project_Form
from .models import Project

response = {}

# Create your views here.
def index(request):
	project = Project.objects.all()
	response['project'] = project

	html = 'Home.html'
	return render(request, html, response)

def addproject(request):
	response['title'] = 'Add Project'
	response['addproject_form'] = Add_Project_Form

	html = 'addproject.html'

	return render(request, html, response)

def saveproject(request):
	form = Add_Project_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['position'] = request.POST['position']
		response['title'] = request.POST['title']
		response['description'] = request.POST['description']
		response['tanggal'] = request.POST.get('tanggal')
		response['kategori'] = request.POST['kategori']
		response['time'] = request.POST['time']
		project = Project(position=response['position'], title=response['title'],description=response['description'], tanggal = response['tanggal'],kategori= response['kategori'], time = response['time'])
		project.save()

		project = Project.objects.all()
		response['project'] = project
		html = 'table.html'
		return render(request, html, response)
	else:
		html = 'table.html'
		return render(request, html, response)

def delete_every(self):
    deleteproject = Project.objects.all().delete()
    response['deleteproject'] = deleteproject
    html = 'table.html'
    return render(self, html, response)

# def message_table(request):
#         project = Project.objects.all()
#         response['project'] = project
#         html = 'story5/table.html'
#         return render(request, html , response)

story4/templates/About.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>About Naufaldi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{%static 'StyleSheet1.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% include "navbar.html" %}
</head>
<body>

<!-- Second Container -->
<div class="container-fluid bg-2 text-center" id="about">
  <h1 class="margin" style="color: #398F9B">ABOUT ME</h1>
  <img src="https://1.bp.blogspot.com/-pJ81SL_I2z0/WkRvxq0ySyI/AAAAAAAA5Ds/msyJr7Y-FSwOzGEv3ljhksOROcaOlecsQCLcBGAs/s1600/x2ee3g06bmyekycfcwrisfkljt0ofwh771kbfeyxugxgdpml29kyjetsh6txe5i9-.jpg" width="75px">
  <h1><br></h1>
  <center>
  <p style="color: black;" "font-family: raleway;" "text-align: center;">My name is Naufaldi Athallah Rifqi. I’m majoring computer science in Faculty of Computer Science University of Indonesia. I’m a Front End Developer with experience coding HTML, CSS, PHP, and JavaScript. I focus on writing clean, elegant and efficient code. </p>
  </center>
</div>

</body>
</html>

story4/templates/Education.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>About Naufaldi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{%static 'StyleSheet1.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% include "navbar.html" %}
</head>
<body>

<!-- Third Container (Grid) -->
<div class="container-fluid bg-3 text-center" id="done">    
  <h1 style="color: white">Here’s what I’ve done so far</h1>
  <svg width="749" height="1" viewBox="0 0 749 1" fill="none" xmlns="http://www.w3.org/2000/svg"> <line y1="0.5" x2="749" y2="0.5" stroke="white"/>
  </svg> <br>
  <svg width="285" height="1" viewBox="0 0 285 1" fill="none" xmlns="http://www.w3.org/2000/svg"> <line y1="0.5" x2="285" y2="0.5" stroke="white"/>
  </svg>
  <center><img id = "uikepal" src = "https://pbs.twimg.com/media/DnXbpKwV4AAHcfp.png:large"></center>
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> SMAN 39 Jakarta <br> 2014-2017</p></center>
  <img id = "uikepal" src="https://i2.wp.com/masqueradestageschool.com/wp-content/uploads/2016/10/3_cQvqKi.png?fit=256%2C256.png">
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> Universitas Indonesia <br> Faculty of Computer Science <br> 2017-now</p></center>
  <img id = "uikepal" src = "https://image.ibb.co/cewsEz/F3_Hbws0w_400x400.png">
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> BEM Fasilkom UI 2018 <br> Staff of Athletic Department <br> 2017-now</p></center>
  <img id = "uikepal" src = "https://image.ibb.co/dHX4SK/BKs_C1_D7_M_400x400.jpg">
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> CS League 2018 <br> Staff of Event <br> 2017-2018</p></center>
  <img id = "uikepal" src = "https://image.ibb.co/nuHhEz/0p_FZav0k_400x400.jpg">
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> COMPFEST X <br> Staff of Seminar <br> 2017-now</p></center>
  <br><br><br><br><br><br><br>
</div>

</body>
</html>

story4/templates/Experience.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>About Naufaldi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{%static 'StyleSheet1.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% include "navbar.html" %}
</head>
<body>

<!-- Third Container (Grid) -->
<div class="container-fluid bg-3 text-center" id="done">    
  <h1 style="color: white">Here’s what I’ve done so far</h1>
  <svg width="749" height="1" viewBox="0 0 749 1" fill="none" xmlns="http://www.w3.org/2000/svg"> <line y1="0.5" x2="749" y2="0.5" stroke="white"/>
  </svg> <br>
  <svg width="285" height="1" viewBox="0 0 285 1" fill="none" xmlns="http://www.w3.org/2000/svg"> <line y1="0.5" x2="285" y2="0.5" stroke="white"/>
  </svg>
  <center><img id = "uikepal" src = "https://pbs.twimg.com/media/DnXbpKwV4AAHcfp.png:large"></center>
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> SMAN 39 Jakarta <br> 2014-2017</p></center>
  <img id = "uikepal" src="https://i2.wp.com/masqueradestageschool.com/wp-content/uploads/2016/10/3_cQvqKi.png?fit=256%2C256.png">
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> Universitas Indonesia <br> Faculty of Computer Science <br> 2017-now</p></center>
  <img id = "uikepal" src = "https://image.ibb.co/cewsEz/F3_Hbws0w_400x400.png">
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> BEM Fasilkom UI 2018 <br> Staff of Athletic Department <br> 2017-now</p></center>
  <img id = "uikepal" src = "https://image.ibb.co/dHX4SK/BKs_C1_D7_M_400x400.jpg">
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> CS League 2018 <br> Staff of Event <br> 2017-2018</p></center>
  <img id = "uikepal" src = "https://image.ibb.co/nuHhEz/0p_FZav0k_400x400.jpg">
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> COMPFEST X <br> Staff of Seminar <br> 2017-now</p></center>
  <br><br><br><br><br><br><br>
</div>

</body>
</html>

story4/templates/Form.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>About Naufaldi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{%static 'StyleSheet1.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% include "navbar.html" %}
</head>
<body>

<div class="container-fluid bg-5" id="thanks">
  <h1>THANKS FOR VISITING MY SITE</h1>
  <h3>Leave your message here</h3> 
  <center>
  <div class="container">
  <div class="col-md-5">
   <div class="form-area">  
        <center>
        <form role="form">
        <br style="clear:both">
                    <h3 style="margin-bottom: 25px; text-align: center;">Contact Form</h3>
            <div class="form-group">
            <input type="text" class="form-control" id="name" name="name" placeholder="Name" required>
          </div>
          <div class="form-group">
            <input type="text" class="form-control" id="email" name="email" placeholder="Email" required>
          </div>
          <div class="form-group">
            <input type="date" class="form-control" id="mobile" name="date" placeholder="Date" required>
          </div>
          <div class="form-group">
            <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject" required>
          </div>
                    <div class="form-group">
                    <textarea class="form-control" type="textarea" id="message" placeholder="Message"></textarea>                    
                    </div>
            
        <button type="button" id="submit" name="submit" class="btn btn-primary pull-right">Submit Form</button>
        </form></center>
    </div>
  </div>
  </div>

</body>
</html>

story4/templates/Home.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>Naufaldi Athallah</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{%static 'StyleSheet1.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% include "navbar.html" %}
</head>
<body>

<div class="container-fluid bg-1 text-center">
  <img src="https://pbs.twimg.com/media/DnWdrT6V4AEoUpD.jpg:large" class="img-responsive img-circle margin" style="display:inline" alt="Bird" width="250" height="250">
  <h1>NAUFALDI ATHALLAH RIFQI</h1>
  <h4>FACULTY OF COMPUTER SCIENCE UNIVERSITAS INDONESIA</h4>
  <br><br><br><br><br>

</body>
</html>

story4/templates/Project.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>About Naufaldi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{%static 'StyleSheet1.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% include "navbar.html" %}

</head>
<body>

<!--fourth container-->
<div class="container-fluid bg-4 text-center" id="projects">
  <h1 class="margin" style="color: #398F9B">PROJECTS</h1>
  <center><div class="trashee"> </div></center>
  <h2 class="margin" style="color: #398F9B">TRA$HEE <br> Co-Founder</h2>
  <center><p style="color: black;" "text-align: center;" "margin-top: 50px"> Platform yang menjadi perantara antara pihak yang membutuhkan sampah dengan pihak yang memiliki sampah berlebih. </p></center>
  <center><div class="carisekolah"></div></center>
  <h2 class="margin" style="color: #398F9B">cariSekolah.id <br> Co-Founder</h2>
  <center><p style="color: black;" "text-align: center;" "margin-top: 50px"> Platform yang berfungsi untuk mempermudah masyarakat mencari sekolah yang favorit. </p></center>
</div>


</body>
</html>

story4/templates/Story3.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>About Naufaldi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{%static 'StyleSheet1.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  {% include "navbar.html" %}
</head>
<body>

<!-- Navbar -->

<!-- First Container -->
<div class="container-fluid bg-1 text-center">
  <!--<h3 class="margin">Who Am I?</h3> -->
  <img src="https://pbs.twimg.com/media/DnWdrT6V4AEoUpD.jpg:large" class="img-responsive img-circle margin" style="display:inline" alt="Bird" width="250" height="250">
  <h1>NAUFALDI ATHALLAH RIFQI</h1>
  <h4>FACULTY OF COMPUTER SCIENCE UNIVERSITAS INDONESIA</h4>
  <br><br><br><br><br>
</div>

<!-- Second Container -->
<div class="container-fluid bg-2 text-center" id="about">
  <h1 class="margin" style="color: #398F9B">ABOUT ME</h1>
  <img src="https://1.bp.blogspot.com/-pJ81SL_I2z0/WkRvxq0ySyI/AAAAAAAA5Ds/msyJr7Y-FSwOzGEv3ljhksOROcaOlecsQCLcBGAs/s1600/x2ee3g06bmyekycfcwrisfkljt0ofwh771kbfeyxugxgdpml29kyjetsh6txe5i9-.jpg" width="75px">
  <h1><br></h1>
  <center>
  <p style="color: black;" "font-family: raleway;" "text-align: center;">My name is Naufaldi Athallah Rifqi. I’m majoring computer science in Faculty of Computer Science University of Indonesia. I’m a Front End Developer with experience coding HTML, CSS, PHP, and JavaScript. I focus on writing clean, elegant and efficient code. </p>
  </center>
</div>

<!-- Third Container (Grid) -->
<div class="container-fluid bg-3 text-center" id="done">    
  <h1 style="color: white">Here’s what I’ve done so far</h1>
  <svg width="749" height="1" viewBox="0 0 749 1" fill="none" xmlns="http://www.w3.org/2000/svg"> <line y1="0.5" x2="749" y2="0.5" stroke="white"/>
  </svg> <br>
  <svg width="285" height="1" viewBox="0 0 285 1" fill="none" xmlns="http://www.w3.org/2000/svg"> <line y1="0.5" x2="285" y2="0.5" stroke="white"/>
  </svg>
  <center><img id = "uikepal" src = "https://pbs.twimg.com/media/DnXbpKwV4AAHcfp.png:large"></center>
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> SMAN 39 Jakarta <br> 2014-2017</p></center>
  <img id = "uikepal" src="https://i2.wp.com/masqueradestageschool.com/wp-content/uploads/2016/10/3_cQvqKi.png?fit=256%2C256.png">
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> Universitas Indonesia <br> Faculty of Computer Science <br> 2017-now</p></center>
  <img id = "uikepal" src = "https://image.ibb.co/cewsEz/F3_Hbws0w_400x400.png">
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> BEM Fasilkom UI 2018 <br> Staff of Athletic Department <br> 2017-now</p></center>
  <img id = "uikepal" src = "https://image.ibb.co/dHX4SK/BKs_C1_D7_M_400x400.jpg">
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> CS League 2018 <br> Staff of Event <br> 2017-2018</p></center>
  <img id = "uikepal" src = "https://image.ibb.co/nuHhEz/0p_FZav0k_400x400.jpg">
  <center><p style="color: white;" "text-align: center;" "margin-top: 50px"><br> COMPFEST X <br> Staff of Seminar <br> 2017-now</p></center>
  <br><br><br><br><br><br><br>
</div>

<!--fourth container-->
<div class="container-fluid bg-4 text-center" id="projects">
  <h1 class="margin" style="color: #398F9B">PROJECTS</h1>
  <center><div class="trashee"> </div></center>
  <h2 class="margin" style="color: #398F9B">TRA$HEE <br> Co-Founder</h2>
  <center><p style="color: black;" "text-align: center;" "margin-top: 50px"> Platform yang menjadi perantara antara pihak yang membutuhkan sampah dengan pihak yang memiliki sampah berlebih. </p></center>
  <center><div class="carisekolah"></div></center>
  <h2 class="margin" style="color: #398F9B">cariSekolah.id <br> Co-Founder</h2>
  <center><p style="color: black;" "text-align: center;" "margin-top: 50px"> Platform yang berfungsi untuk mempermudah masyarakat mencari sekolah yang favorit. </p></center>
</div>

<div class="container-fluid bg-5" id="thanks">
  <h1>THANKS FOR VISITING MY SITE</h1>
  <h3>Leave your message here</h3> 
  <center>
  <div class="container">
  <div class="col-md-5">
   <div class="form-area">  
        <center>
        <form role="form">
        <br style="clear:both">
                    <h3 style="margin-bottom: 25px; text-align: center;">Contact Form</h3>
            <div class="form-group">
            <input type="text" class="form-control" id="name" name="name" placeholder="Name" required>
          </div>
          <div class="form-group">
            <input type="text" class="form-control" id="email" name="email" placeholder="Email" required>
          </div>
          <div class="form-group">
            <input type="date" class="form-control" id="mobile" name="date" placeholder="Date" required>
          </div>
          <div class="form-group">
            <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject" required>
          </div>
                    <div class="form-group">
                    <textarea class="form-control" type="textarea" id="message" placeholder="Message"></textarea>                    
                    </div>
            
        <button type="button" id="submit" name="submit" class="btn btn-primary pull-right">Submit Form</button>
        </form></center>
    </div>
  </div>
  </div>
</body>
</html>

story4/templates/navbar.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>About Naufaldi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="stylesheet" type="text/css" href="{%static 'StyleSheet1.css' %}" /> -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  

</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="{% url 'form' %}" id="name">HELLO</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'home' %}">HOME</a></li>
        <li><a href="{% url 'about' %}">ABOUT</a></li>
        <li><a href="{% url 'experience' %}">EXPERIENCES</a></li>
        <li><a href="{% url 'project' %}">PROJECTS</a></li>
        <li><a href="{% url 'story5:saveproject' %}">SCHEDULE</a>
      </ul>
    </div>
  </div>
</nav>

</body>
</html>

story5/templates/addproject.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  {% include "navbar.html" %}
</head>
<body>

<section>
  <div>
        <div>
          <form id="form" method="POST" action="{% url 'story5:saveproject' %}">
            {% csrf_token %}
            {{ addproject_form.as_p }}

            <input id="submit" type="submit" class="btn btn-lg btn-info" value="Submit">
          </form>
        </div>
    </div>
</section>

</body>
</html>

story5/templates/navbar.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>About Naufaldi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{%static 'StyleSheet1.css' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="{% url 'form' %}" id="name">HELLO</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'home' %}">HOME</a></li>
        <li><a href="{% url 'about' %}">ABOUT</a></li>
        <li><a href="{% url 'experience' %}">EXPERIENCES</a></li>
        <li><a href="{% url 'project' %}">PROJECTS</a></li>
      </ul>
    </div>
  </div>
</nav>

</body>
</html>